name: JAVA-Maven CI

on:
 push:
    branches: [ master ]
  

jobs:
  build-job: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
